// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5TO9dPa8R7oall-tW-OmtgjaeaftbgSU',
    appId: '1:331372763701:web:810846293a08575c63af7c',
    messagingSenderId: '331372763701',
    projectId: 'sipanitia-cc30e',
    authDomain: 'sipanitia-cc30e.firebaseapp.com',
    storageBucket: 'sipanitia-cc30e.firebasestorage.app',
    measurementId: 'G-JXWM8C1BT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6UfB0pXcX3fPfXBeyVhbG-MtawSSbYSs',
    appId: '1:331372763701:android:1384df1544d874b563af7c',
    messagingSenderId: '331372763701',
    projectId: 'sipanitia-cc30e',
    storageBucket: 'sipanitia-cc30e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDefMD5US8wcFJCEdN1sgnYn5ZK86ooZx0',
    appId: '1:331372763701:ios:61e01a6594eb700863af7c',
    messagingSenderId: '331372763701',
    projectId: 'sipanitia-cc30e',
    storageBucket: 'sipanitia-cc30e.firebasestorage.app',
    iosBundleId: 'com.example.sipanitia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDefMD5US8wcFJCEdN1sgnYn5ZK86ooZx0',
    appId: '1:331372763701:ios:61e01a6594eb700863af7c',
    messagingSenderId: '331372763701',
    projectId: 'sipanitia-cc30e',
    storageBucket: 'sipanitia-cc30e.firebasestorage.app',
    iosBundleId: 'com.example.sipanitia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5TO9dPa8R7oall-tW-OmtgjaeaftbgSU',
    appId: '1:331372763701:web:1501d2e38fb0e09363af7c',
    messagingSenderId: '331372763701',
    projectId: 'sipanitia-cc30e',
    authDomain: 'sipanitia-cc30e.firebaseapp.com',
    storageBucket: 'sipanitia-cc30e.firebasestorage.app',
    measurementId: 'G-QEL2L8ZNWJ',
  );
}
